### ISSUE TITLE
Installing rGEDIsimulator

### ISSUE THREAD

**Issue by jean-allen** [caiohamamura/rGEDIsimulator#2]
Hi! I was wondering if there are separate instructions for installing rGEDIsimulator now that it's separate from rGEDI? Thank you!

**Comment by caiohamamura** [comment]
Not yet, but it should work just the same as before, if you get any trouble
you can open an issue. I will get my hands on rGEDI next months, so I'll
probably update that.

**Comment by jean-allen** [comment]
Awesome, thank you so much!

**Comment by caiohamamura** [comment]
I just included the instructions on the rGEDI main readme https://github.com/carlos-alberto-silva/rGEDI/?tab=readme-ov-file#simulating-gedi-full-waveform-data-from-airborne-laser-scanning-als-3-d-point-cloud-and-extracting-canopy-derived-metrics

**Comment by jean-allen** [comment]
Thank you! I was very new to R when I asked this so I really appreciate the clarity :)
