### ISSUE TITLE
Failed to install rGEDIsimulator package from git

### ISSUE THREAD

**Issue by Liuhl555** [caiohamamura/rGEDIsimulator#3]
Hi!
I've tried different ways to install the rGEDIsimulator package but none works

![image](https://github.com/caiohamamura/rGEDIsimulator/assets/80765014/ae93635d-71b4-42c9-9587-7f350c034036)
![image](https://github.com/caiohamamura/rGEDIsimulator/assets/80765014/d1d4a4fe-4c86-47ca-a05a-fa9fa464c464)
![image](https://github.com/caiohamamura/rGEDIsimulator/assets/80765014/b63670ce-a434-478a-8c10-5a4494f76b36)
It seems Git encountered an issue while attempting to download packages from GitHub
My git is confiurged and no network issues. ChatGPT says there may be some problem with Git or github
Could you please tell me how solve this problem?

Thanks!

**Comment by caiohamamura** [comment]
Can you install any package at all from GitHub? 
If you run `system("git --version")` does that work? What is the output?

**Comment by Liuhl555** [comment]
Thank you for your reply!

I successfully installed the rGEDI package by the `devtools::install_git()` method  days before, but I can't install any package by the same way now，and `devtools::install_github()` method also doesn't work for `rGEDIsimulator`  package but works for other packages .
And I get the `git version 2.43.0.windows.1` when run `system("git --version")` , seems  normal?

Thanks!

**Comment by WangGR1** [comment]
I'm also having the same issue
ERROR: compilation failed for package 'rGEDIsimulator'
* removing 'D:/r/R-4.3.3/library/rGEDIsimulator'
Warning message:
In i.p(...) :
  安装程序包‘C:/Users/WGR/AppData/Local/Temp/RtmpoFKUyY/file3cb0e00ddf/rGEDIsimulator_0.1.1.tar.gz’时退出狀態的值不是0
Has your problem been solved, can you tell me how it was solved?

**Comment by MiZu-max** [comment]
Hello, I met the same problem as you, may I ask if you finally solved it? What method was used to solve it? Thanks sincerely!

**Comment by caiohamamura** [comment]
Hello, is it windows? If so you need to install the appropriate version of [`rtools`](https://cran.r-project.org/bin/windows/Rtools/)

**Comment by MiZu-max** [comment]
您好！我是易启亮，您的邮件已经收到，我会及时查看并反馈，谢谢！

**Comment by MiZu-max** [comment]
Yeah it is Windows. I have tried rtools but it didn't work.

**Comment by caiohamamura** [comment]
The message from before is regarding rtools, if you have a different error message you need to post a different issue

**Comment by MiZu-max** [comment]
Thank you for your answer. Sorry, my statement may be ambiguous, I mean, I tried to install the rgedi package using `Rtools 4.3`, but still couldn't. The error I encountered was almost identical to the error mentioned by user liuhongliang-818 above. And the version of git I use is `git version 2.35.0.windows.1`. It also didn't work when I tried to install the `rGEDIsimulator` package by downloading the zip package locally. It didn't report an error, but it didn't install successfully either.

**Comment by liuhongliang-818** [comment]
> Thank you for your answer. Sorry, my statement may be ambiguous, I mean, I tried to install the rgedi package using `Rtools 4.3`, but still couldn't. The error I encountered was almost identical to the error mentioned by user liuhongliang-818 above. And the version of git I use is `git version 2.35.0.windows.1`. It also didn't work when I tried to install the `rGEDIsimulator` package by downloading the zip package locally. It didn't report an error, but it didn't install successfully either.↳

**If you're using a VPN when installing the `rGEDIsimulator` package from git or github，I suggest you to set up proxy by the command `Sys.setenv(http_proxy = "https://your_proxy_ip:port")` before you install the package.**
By setting up proxy the erro:`Failed to install 'unknow package' from Git:Command failed (128)` may be  solved.

But I encountered the same issue just as @WangGR1 referred above

**Comment by MiZu-max** [comment]
> > Thank you for your answer. Sorry, my statement may be ambiguous, I mean, I tried to install the rgedi package using `Rtools 4.3`, but still couldn't. The error I encountered was almost identical to the error mentioned by user liuhongliang-818 above. And the version of git I use is `git version 2.35.0.windows.1`. It also didn't work when I tried to install the `rGEDIsimulator` package by downloading the zip package locally. It didn't report an error, but it didn't install successfully either.↳
> 
> **If you're using a VPN when installing the `rGEDIsimulator` package from git or github，I suggest you to set up proxy by the command `Sys.setenv(http_proxy = "https://your_proxy_ip:port")` before you install the package.** By setting up proxy the erro:`Failed to install 'unknow package' from Git:Command failed (128)` may be solved.
> 
> But I encountered the same issue just as @WangGR1 referred above

Thanks for your advice. I have tried it but I was faced with a new error: `Failed to install 'rGEDIsimulator' from Git:Command failed (128)`
![image](https://github.com/caiohamamura/rGEDIsimulator/assets/72400977/7df49606-7f43-4cb7-867f-b4ad1f12c18a)

**Comment by cHen2th** [comment]
Have you solved this problem？I tried to solve this problem on Taobao, but the seller said that the package needs to be modified in the source code to be installed successfully.

**Comment by cHen2th** [comment]
I also encountered this issue before, and now I have successfully resolved it. I have re downloaded the old versions of R and Rtools, and deleted the original R, Rtools, and RStudio (but the reinstalled RStudio version did not change). Here, I used the Geek tool to delete them, and also deleted the registry related content of these software. The reinstalled versions are as follows: R-4.2.2 win. exe, rtools 42-5355-5357. exe, RStudio 2023.12.1-402. exe, and during this reinstallation, I did not manually add any environment variables, only changed the installation path (in full English). I hope this is helpful to you.

**Comment by Liuhl555** [comment]
> I also encountered this issue before, and now I have successfully resolved it. I have re downloaded the old versions of R and Rtools, and deleted the original R, Rtools, and RStudio (but the reinstalled RStudio version did not change). Here, I used the Geek tool to delete them, and also deleted the registry related content of these software. The reinstalled versions are as follows: R-4.2.2 win. exe, rtools 42-5355-5357. exe, RStudio 2023.12.1-402. exe, and during this reinstallation, I did not manually add any environment variables, only changed the installation path (in full English). I hope this is helpful to you.↳

Thank you! I've tried your methord but still failed to install the package. Are you using Windows or Linux? Did you use a VPN when installing the package?

**Comment by caiohamamura** [comment]
Thank you for sharing @cHen2th, we actually need to update the package to run in 4.3 version. It is quite a nightmare to maintain compiled packages depending on third party libraries, every time the rtools version changes we have to update the 'Makevars.ucrt' file. I will soon try to update that.

**Comment by MiZu-max** [comment]
Thank you very much for your advice @cHen2th , and I have successfully solved my problem according to your suggestions.

**Comment by cHen2th** [comment]
> Thank you for sharing @cHen2th, we actually need to update the package to run in 4.3 version. It is quite a nightmare to maintain compiled packages depending on third party libraries, every time the rtools version changes we have to update the 'Makevars.ucrt' file. I will soon try to update that.

Thank you for your efforts

**Comment by Liuhl555** [comment]
> I also encountered this issue before, and now I have successfully resolved it. I have re downloaded the old versions of R and Rtools, and deleted the original R, Rtools, and RStudio (but the reinstalled RStudio version did not change). Here, I used the Geek tool to delete them, and also deleted the registry related content of these software. The reinstalled versions are as follows: R-4.2.2 win. exe, rtools 42-5355-5357. exe, RStudio 2023.12.1-402. exe, and during this reinstallation, I did not manually add any environment variables, only changed the installation path (in full English). I hope this is helpful to you.↳

Thank you! I've tried your method(reinstalled R-4.2.2 win. exe, rtools 42-5355-5357. exe, RStudio 2023.12.1-402. exe) but encountered  `ERROR: dependency 'rGEDI' is not available for package 'rGEDIsimulator'` .The dependency package 'rGEDI'  seems not available for  R-4.2.2 .Have you encountered this problem and how do you solve it?
![image](https://github.com/caiohamamura/rGEDIsimulator/assets/80765014/c8170702-8da4-46ec-9c4d-4e1167d49efd)

**Comment by caiohamamura** [comment]
Install rGEDI first, `remotes::install_github("carlos-alberto-silva/rGEDI")`

**Comment by Liuhl555** [comment]
> Install rGEDI first, `remotes::install_github("carlos-alberto-silva/rGEDI")`↳

Thank you for your advice ! I finally installed the package successfully ！
Appreciate all your efforts!

**Comment by caiohamamura** [comment]
I have updated the `Makevars.ucrt`, now it should work with the 4.3 version.
